[mypy]
python_version = 3.9
ignore_missing_imports = True
warn_unused_ignores = False
warn_redundant_casts = False
warn_no_return = False
no_site_packages = True
# Limit to keeper stress framework paths
files = tests/stress/keeper/framework, tests/stress/keeper/plugins, tests/stress/keeper/tools
