ATTACH TABLE _ UUID '6a7bf4d6-2813-4565-b076-2f2eacb24ba0'
(
    `hostname` LowCardinality(String) COMMENT 'The hostname where the crash occurred.',
    `event_date` Date COMMENT 'The date of the crash.',
    `event_time` DateTime COMMENT 'The time of the crash.',
    `timestamp_ns` UInt64 COMMENT 'Timestamp of the event with nanoseconds.',
    `signal` Int32 COMMENT 'Signal number.',
    `thread_id` UInt64 COMMENT 'Thread ID.',
    `query_id` String COMMENT 'Query ID.',
    `trace` Array(UInt64) COMMENT 'Stack trace at the moment of crash. Each element is a virtual memory address inside ClickHouse server process.',
    `trace_full` Array(String) COMMENT 'Stack trace at the moment of crash. Each element contains a called method inside ClickHouse server process.',
    `version` String COMMENT 'ClickHouse server version.',
    `revision` UInt32 COMMENT 'ClickHouse server revision.',
    `build_id` String COMMENT 'BuildID that is generated by compiler.'
)
ENGINE = MergeTree
ORDER BY (event_date, event_time)
SETTINGS index_granularity = 8192
COMMENT 'Contains information about stack traces for fatal errors. The table does not exist in the database by default, it is created only when fatal errors occur.\n\nIt is safe to truncate or drop this table at any time.'
