ATTACH TABLE _ UUID 'dc065fa4-66e5-4174-aecf-72466a9a5f49'
(
    `hostname` LowCardinality(String) COMMENT 'Hostname of the server executing the query.',
    `event_date` Date COMMENT 'The date when the thread has finished execution of the query.',
    `event_time` DateTime COMMENT 'The date and time when the thread has finished execution of the query.',
    `event_time_microseconds` DateTime64(6) COMMENT 'The date and time when the thread has finished execution of the query with microseconds precision.',
    `query_start_time` DateTime COMMENT 'Start time of query execution.',
    `query_start_time_microseconds` DateTime64(6) COMMENT 'Start time of query execution with microsecond precision.',
    `query_duration_ms` UInt64 COMMENT 'Duration of query execution.',
    `read_rows` UInt64 COMMENT 'Number of read rows.',
    `read_bytes` UInt64 COMMENT 'Number of read bytes.',
    `written_rows` UInt64 COMMENT 'For INSERT queries, the number of written rows. For other queries, the column value is 0.',
    `written_bytes` UInt64 COMMENT 'For INSERT queries, the number of written bytes. For other queries, the column value is 0.',
    `memory_usage` Int64 COMMENT 'The difference between the amount of allocated and freed memory in context of this thread.',
    `peak_memory_usage` Int64 COMMENT 'The maximum difference between the amount of allocated and freed memory in context of this thread.',
    `thread_name` LowCardinality(String) COMMENT 'Name of the thread.',
    `thread_id` UInt64 COMMENT 'Internal thread ID.',
    `master_thread_id` UInt64 COMMENT 'OS initial ID of initial thread.',
    `current_database` LowCardinality(String) COMMENT 'Name of the current database.',
    `query` String COMMENT 'Query string.',
    `normalized_query_hash` UInt64 COMMENT 'The hash of normalized query - with wiped constanstans, etc.',
    `is_initial_query` UInt8 COMMENT 'Query type. Possible values: 1 — Query was initiated by the client, 0 — Query was initiated by another query for distributed query execution.',
    `user` LowCardinality(String) COMMENT 'Name of the user who initiated the current query.',
    `query_id` String COMMENT 'ID of the query.',
    `address` IPv6 COMMENT 'IP address that was used to make the query.',
    `port` UInt16 COMMENT 'The client port that was used to make the query.',
    `initial_user` LowCardinality(String) COMMENT 'Name of the user who ran the initial query (for distributed query execution).',
    `initial_query_id` String COMMENT 'ID of the initial query (for distributed query execution).',
    `initial_address` IPv6 COMMENT 'IP address that the parent query was launched from.',
    `initial_port` UInt16 COMMENT 'The client port that was used to make the parent query.',
    `initial_query_start_time` DateTime COMMENT 'Start time of the initial query execution.',
    `initial_query_start_time_microseconds` DateTime64(6) COMMENT 'Start time of the initial query execution ',
    `interface` UInt8 COMMENT 'Interface that the query was initiated from. Possible values: 1 — TCP, 2 — HTTP.',
    `is_secure` UInt8 COMMENT 'The flag which shows whether the connection was secure.',
    `os_user` LowCardinality(String) COMMENT 'OSs username who runs clickhouse-client.',
    `client_hostname` LowCardinality(String) COMMENT 'Hostname of the client machine where the clickhouse-client or another TCP client is run.',
    `client_name` LowCardinality(String) COMMENT 'The clickhouse-client or another TCP client name.',
    `client_revision` UInt32 COMMENT 'Revision of the clickhouse-client or another TCP client.',
    `client_version_major` UInt32 COMMENT 'Major version of the clickhouse-client or another TCP client.',
    `client_version_minor` UInt32 COMMENT 'Minor version of the clickhouse-client or another TCP client.',
    `client_version_patch` UInt32 COMMENT 'Patch component of the clickhouse-client or another TCP client version.',
    `script_query_number` UInt32 COMMENT 'A sequential query number in a multi-query script.',
    `script_line_number` UInt32 COMMENT 'A line number in a multi-query script where the current query starts.',
    `http_method` UInt8 COMMENT 'HTTP method that initiated the query. Possible values: 0 — The query was launched from the TCP interface, 1 — GET method was used., 2 — POST method was used.',
    `http_user_agent` LowCardinality(String) COMMENT 'The UserAgent header passed in the HTTP request.',
    `http_referer` String COMMENT 'HTTP header `Referer` passed in the HTTP query (contains an absolute or partial address of the page making the query).',
    `forwarded_for` String COMMENT 'HTTP header `X-Forwarded-For` passed in the HTTP query.',
    `quota_key` String COMMENT 'The \'quota key\' specified in the quotas setting.',
    `distributed_depth` UInt64 COMMENT 'How many times a query was forwarded between servers.',
    `revision` UInt32 COMMENT 'ClickHouse revision.',
    `ProfileEvents` Map(LowCardinality(String), UInt64) COMMENT 'ProfileEvents that measure different metrics for this thread. The description of them could be found in the table system.events.',
    `ProfileEvents.Names` Array(LowCardinality(String)) ALIAS mapKeys(ProfileEvents),
    `ProfileEvents.Values` Array(UInt64) ALIAS mapValues(ProfileEvents)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(event_date)
ORDER BY (event_date, event_time)
SETTINGS index_granularity = 8192
COMMENT 'Contains information about threads that execute queries, for example, thread name, thread start time, duration of query processing.\n\nIt is safe to truncate or drop this table at any time.'
